### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#14]
Description

1. Password error message incorrect.
2. Forgot password title missing. In task only ignore functionality mention.

Below is SS

![bug1](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/4971e362-7e85-4e99-886f-fb1d81bbe609)

Related to 
#6

**Comment by namratacn** [comment]
Bug fixed.
