### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#15]
Description 

Google sign button logo not show. if keyboard open or not. Screen not able to scroll in small device please check.

Below is SS

![bug2](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/aaa55179-fe26-467e-871c-7e3d231c661c)

Related to 
#6

**Comment by namratacn** [comment]
Scrolling issue bug fixed.
