### ISSUE TITLE
Error message color incorrect

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#17]
Description 

Please check login screen error color code.

Below is SS

![Screenshot 2023-08-14 at 4 17 22 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/31251039-ef2b-4c2f-93ec-15875df0e391)

Related to
#16

**Comment by namratacn** [comment]
Error msg color incorrect Bug fixed.
