### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#18]
Description 

Please hint and label text give different. Please refer login screen.

Below is SS

![Screenshot 2023-08-14 at 4 18 49 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/4ccf0630-0928-4417-8500-313d2abf46fb)

Related to 
#16

**Comment by HarshPanchalInfusion** [comment]
Done

**Comment by HarshPanchalInfusion** [comment]
Done
