### ISSUE TITLE
Add Doctor screen ui issue

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#19]
Description

- [ ]  #1 As per discussion we have to mention email and phone number verification. In UI show email and phone number right side show a label verify. if both done then show verified. That things are missing in this UI.

- [ ]  #2 Please hint and label text give different. Please refer login screen.

- [ ] Submit button UI is incorrect please refer SS

| #1  | #2 | #3 |
| ------------- | ------------- | ------------- |
|![Screenshot 2023-08-14 at 4 21 37 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/6055e8a9-35a4-4ed0-b294-f458fec3fe10)|![Screenshot 2023-08-14 at 4 18 49 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/4ccf0630-0928-4417-8500-313d2abf46fb) |![Screenshot 2023-08-14 at 4 55 55 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/bf6143d3-4986-454f-b968-87bd1aab9f42)|
#16

**Comment by HarshPanchalInfusion** [comment]
Done
