### ISSUE TITLE
Add Doctor screen scrolling not working

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#20]
Description 

User not able to scroll add doctor screen.

![Screenshot 2023-08-14 at 4 23 06 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/b546855c-eeae-4433-ae48-59a29cc21a73)

Related to
#16

**Comment by HarshPanchalInfusion** [comment]
Done
