### ISSUE TITLE
Error message color code is incorrect

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#23]
Description 

Please update error message color code right now it show in blue color.

Below is SS
![Screenshot 2023-08-17 at 11 23 26 AM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/8bb510ab-6d21-4b40-b217-d8570e773db2)

**Comment by namratacn** [comment]
Bug fixed.
