### ISSUE TITLE
Error not clear when user navigate to signUp screen then back to login screen

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#24]
Description

Please clear data and error when user navigate to other screen.

Steps- 
1. put wrong value both field show error
2. Then click on signup 
3. Back to login again show that error as well data show.

Clear data.

Related to
#6 

![Uploading Screenshot 2023-08-17 at 11.47.02 AM.png…]()

**Comment by namratacn** [comment]
clear data and error when user navigate to other screen bug fixed.
