### ISSUE TITLE
Signup issue

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#34]
Description,

In signup screen password and confirm pass word not working.

Step 1. Enter password
Step 2. Enter same password in confirmation password change it show the error msg that is right also button disable.
Step 3. Enter same password in confirmation password and change value in old password then not show any error also button enable and data submit.

![Screenshot 2023-08-29 at 11 19 51 AM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/8d4e1c49-a035-495b-a5d4-63e0debb4928)

Related to,
#9

**Comment by namratacn** [comment]
In signup screen password and confirm pass word not working issue fixed.
