### ISSUE TITLE
Add user screen

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#35]
Description,

1. Please add action bar and title add user.
2. Please mention equal space between fields.
3. If date and month between 1 to 9 show please add 0 in that date like 01-08-2023
4. Data reset issue
5. api call for verify phone call 10 sec

![Screenshot 2023-08-29 at 11 25 39 AM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/45d36639-c715-4b61-915f-afb8bb9f61b1)

Related to
#9

**Comment by namratacn** [comment]
add action bar and title add user.
mention equal space between fields.
If date and month between 1 to 9 show please add 0 in that date like 01-08-2023
Data reset issue
api call for verify phone call 10 sec
All the bugs and issue fixed.
