### ISSUE TITLE
Admin screen bugs

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#39]
Please address below Admin screen bugs

- [x] Do not show back icon on toolbar
- [x] Back should not take user to login screen it should close the app
- [x] Long email should not cut make it elipse

Relates to #29 

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by vikas-infusion** [comment]
Task done
