### ISSUE TITLE
Feature - Add back icon

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#45]
**Is your feature request related to a problem? Please describe.**
Please add back icon with title in action-bar in otp screen

**Add your acceptation criteria.**
user press on backIcon move to previous screen.

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Bug fixed.
