### ISSUE TITLE
Feature - [User] Doctor Listing screen

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#46]
**Is your feature request related to a problem? Please describe.**
When user successfully verify all the details and move to dashboard screen that time show a doctor list.

**Add your acceptation criteria.**
Show Doctor listing

UI
https://drive.google.com/file/d/10Pz6Id1SWGUM1aTQlC-CTffAutCfqnz4/view?usp=drive_link

- [x] List item should contain doctor name, gender, rating, degree  and  View button
- [x] On view Click user should navigate to book appointment screen

**Estimation - 8 hours**

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
1. Designed Ui for doctor listing.
2. Done Getting all data of doctors through api and showing in doctor listing screen.
3. Done navigation on book appointment screen on click of view button.
