### ISSUE TITLE
Feature - [User] Search doctors on doctors listing screen

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#47]
User should able to search doctors from list of doctors 

**Add your acceptation criteria.**

- [x] Minimum 3 character should be entered before search start
- [x] User should be able to search based on Name, gender and degree

**Estimation - 6 hours**
### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
1. Completed minimum 3 characters should be entered after that search will be started.
2. Completed user can search name, gender and degree based on that displayed the result.
3. Done some Ui changes of previous task(listing doctor screen).
