### ISSUE TITLE
Feature - [User] Book appointment screen

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#48]
User can book doctor appoint ment 

Screen UI link
https://drive.google.com/file/d/1gy8l0zEG-O7PDAliVfRsWTOfR0I2tthe/view?usp=drive_link

- [x] Display all doctor display here
- [x] User should be able see 15 days date only
- [x] If date or time slot is already booked then it would be disable
- [x] Book appointment button would enable by default 
- [x] Show validation if user has not selected date and time slot
- [x] Show conformation before appointment book
- [x] Once appointment is booked it would be in pending for confirmation state

**Estimation - 20 hours**

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by HarshPanchalInfusion** [comment]
Completed other functionality in 3.5 hour
Work on date wise time availability feature 4.5 hour (due to how to get data & show)
