### ISSUE TITLE
Add Doctor Screen

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#5]
**Create screen for adding doctor using  [screen](https://drive.google.com/file/d/1CrsR4P_3LviwrtNSoOD5XPg0GT4gvAjs/view?usp=drive_link).** 

ACs

- [ ] Screen will have field **userId, name, email, address(ignore in UI), contactNumber, degree(ignore in UI), speciality(ignore in UI), availableDate(ignore in UI), availableTime(ignore in UI), images(ignore in UI), isNotificationEnable(toggle), isEmailVerified(ignore in UI, pass value as false, ), isPhoneNumverVerifiedd(ignore in UI, pass value as false), isDoctor(ignore in UI pass value as true), isAdmin(ignore in UI pass value as false)**
- [x] Each fields  which  are in UI aremandatory so it should have validation, submit button will enabled after user enter valid data in all fields.
- [x] Name validation - Should contain at least 3 character. validation message "Name should contain at least 3 characters" 
- [x] Email - no null And valid email
- [x] On submit click data should save in firestore table name **user_data**
- [x] After data added successfully it should display "Doctor information successfully saved."
- [x] User should move to login screen

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by HarshPanchalInfusion** [comment]
Create a Pull request for add doctor screen.
