### ISSUE TITLE
Feature - [Doctor] - Home page

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#50]
When doctor is logged in he/she would be landed on doctor's home 

### ACs

- [x] This screen will have tabs Appointment, Request, Profile.
- [x] Create and display blank fragment for each tabs.

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Doctor logged in moved to doctors dashboard screen. This screen will have tabs Appointment, Request, Profile.
 Create and display blank fragment for each tabs.  Also completed for user dashboard as well.
