### ISSUE TITLE
Feature - [Doctor] Appointment tab - UI

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#54]
When doctor logged in by default Appointment tab should be selected

Please refer below UI
https://drive.google.com/file/d/1YMlpPHr5RM1BOWDfmWAjr4GxpojartBR/view?usp=drive_link

### ACs

- [x] Appointment would be display date wise
- [x] Past appointment should not displayed
- [x] View all button should take user to new screen(blank fragment)

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Appointments displayed date wise
 Past appointment not displayed
 View all button navigate to  new screen(blank fragment)
