### ISSUE TITLE
Feature - Differentiate Authenticator and Post authenticator packages    

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#59]
Refactor packages in correct manner so that it can be easy to manage going forward

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Refactor packages in correct manner so that it can be easy to manage going forward
