### ISSUE TITLE
User login screen

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#6]
Create screen for User login using [screen](https://drive.google.com/file/d/1CrsR4P_3LviwrtNSoOD5XPg0GT4gvAjs/view?usp=drive_link).

- [x] Screen will have Logo, Login title, email input field, password input field, forgot password title(ignore functionality for now), Log in button, Don't have account Sign up label.
- [x] Fields are mandatory so display error messages when user type email and password. Email error - "Please enter valid email", Password - Password should contain atleast one small, one capital, one special symbol and should contain at least 8 characters.
- [ ] Sign in button will be enabled after user enter valid email and password.
- [x] Sign up label would be clickable and should take user to Signup screen Home screen.
- [x] In case of failure, display dialog with information - for wrong credentials "You have entered wrong email or password"

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Implemented login screen.
Added the validation for email and password.
when user click on login button it check the email and password firebase authentication. if email and password is correct then navigate to addUserProfile screen. else its show the dialog box foe incorrect email or password.
Also put the one SignUp lable for navigate to Registration screen.

**Comment by vikas-infusion** [comment]
Bugs:

#1. Login button not working. When user fill all data and click on login button then if error exist then remove it and progress indicator show.

Below is SS.



![Screenshot_1692005960](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/e5537945-bfdf-4545-aa6d-84098ee966da)

**Comment by vikas-infusion** [comment]
#2 Google sign logo not show. if keyboard open or not. Screen not able to scroll in small device please check.



![Screenshot 2023-08-14 at 3 12 51 PM](https://github.com/jaykishan-sewak/doctor-appoint-app/assets/71261888/8043a9c3-ab98-40dc-b43e-8c8b0ed6ea3a)
