### ISSUE TITLE
Bug -[UI] Some UI issue at user and doctor side.

### ISSUE THREAD

**Issue by vikas-infusion** [jaykishan-sewak/doctor-appoint-app#71]
**Describe the bug**
- Please check bottom bar option for user. 1. Search 2.My Appointments 3. Profile

- When user select any option bar please change background color. In both user & doctor side.

- Doctor side first tab Appointments by default selected and show only Approve Appointments.

- Add icon
  - name for user
  - contact for phone
  - age 

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
Fixed bug.
