### ISSUE TITLE
User Sign up

### ISSUE THREAD

**Issue by jaykishan-sewak** [jaykishan-sewak/doctor-appoint-app#9]
### User sign up [screen design](https://drive.google.com/file/d/1CrsR4P_3LviwrtNSoOD5XPg0GT4gvAjs/view?usp=drive_link)
ACs

- [x] This screen will contain email, password and confirm password fields.
- [x] All fields are mandatory so add validations, for email and password use same validation used in login screen after success sign up save data to **user_data** table
- [x] Once user is enters correct detail and do sign up then take user to login screen
- [x] Once user in the app check if **isUserVerified** flag is true or false(also co ordinate with @HarshPanchalInfusion as he will work on same functionality for doctor) if value is true then take user to Home screen otherwise  show information popup with text "Please complete your profile to continue" with Ok and Cancel button if user press Ok then take user to update profile button and on pressing cancel exit the app.
- [x] User will have fields - **name**,**email**(not editable and with label "Verified" with green color on right side not clickable) , **address**, **contacrNumber**(clickable label "Verify" with yellow color), dob - All fields are mandatory so show validation accordingly.
- [x] Validation criteria - name and address - length must be more then 3 characters, dob - not null
- [x] Validation message name - "Name must have at least there characters" 
- [x] Validation message address - "Address must have at least there characters" 
- [x] Validation message dob - "Date of birth can not be empty" 
- [x] For mobile verification user firebase otp service, when user click on **Verify** label on Contact number Field then take user to OTP screen
- [x] Design for OTP screen
- [x] Once OTP is verified then take user back to Profile screen and after all validations passed save user data to user_data table

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

**Comment by namratacn** [comment]
1. Completed tasks.
2. Fixed the issues.
3. Updated Ui.
4. Fixed bugs.
5. Done PR changes.
